Case:
Create numpy array from your inputted full name in the form of numbers based on order in alphabets. You can use this translater to change from alphabet to number: 
```py
letter_to_word = {'a': 1, 'c': 3, 'b': 2, 'e': 5, 'd': 4, 'g': 7, 'f': 6, 'i': 9, 'h': 8, 'k': 11, 'j': 10, 'm': 13, 'l': 12, 'o': 15, 'n': 14, 'q': 17, 'p': 16, 's': 19, 'r': 18, 'u': 21, 't': 20, 'w': 23, 'v': 22, 'y': 25, 'x': 24, 'z': 26}
```
Also add repetition on the number based on your inputted number.
Example:
inputted full name = 'Jenny'<br>
repeated = 4 times<br>
result:<br>
```
[[10  5 14 14 25]
 [10  5 14 14 25]
 [10  5 14 14 25]
 [10  5 14 14 25]]
```

In [11]:
import numpy as np

letter_to_word = {'a': 1, 'c': 3, 'b': 2, 'e': 5, 'd': 4, 'g': 7, 'f': 6, 'i': 9, 'h': 8, 'k': 11, 'j': 10, 'm': 13, 'l': 12, 'o': 15, 'n': 14, 'q': 17, 'p': 16, 's': 19, 'r': 18, 'u': 21, 't': 20, 'w': 23, 'v': 22, 'y': 25, 'x': 24, 'z': 26}

name = str(input("Silahkan masukan nama Anda : "))
ulangi = input("Diulang : ")

angka = []
for x in name:
    angka = angka + [letter_to_word[x]]

a = np.full ((ulangi, len(angka)), [angka], dtype=int)
print (a)

Silahkan masukan nama Anda : fie
Diulang : 2


TypeError: 'str' object cannot be interpreted as an integer